### ISSUE TITLE
Server error when running syntax submodule

### ISSUE THREAD

**Issue by sophiasw1** [sentspace/sentspace#9]
<img width="700" alt="Screenshot 2023-08-08 152342" src="https://github.com/sentspace/sentspace/assets/141785997/03c84d60-ec0e-4db2-aa04-ed81856ea204">

**Comment by aalok-sathe** [comment]
hi @sophiasw1, thanks for creating an issue here!
- I just pushed an updated docker image today at https://hub.docker.com/r/fedorenkolanguagelab/evlabwebapps-sentspace. would you mind updating your copy of the repo and re-running the singularity script so it knows to pull the more recent image?
- In addition, could you make sure you are running an instance of the syntax server in order to obtain the syntax/contextual features? please see here: https://github.com/sentspace/sentspace-syntax-server
